name: FallCraftSystem
version: ${project.version}
main: fallcraftsystem.core.FallCraftSystem
api-version: 1.8.8
depend: [WorldGuard]
commands:
  setwarp:
    description: Defino um novo warp.
    permission: fallcraft.module.warp.admin
    usage: Use /setwarp <Name> <Position> [Permission] para definir um warp.
  delwarp:
    description: Deleta um warp.
    permission: fallcraft.module.warp.admin
    usage: Use /delwarp <Name> tpara deletar um warp.
  warp:
    description: Abre o menu de warps.
    permission: fallcraft.module.warp.use
    usage: Use /warp <warp name> to teleport.
  warplist:
    description: See the all warps.
    permission: fallcraft.module.warp.list
    usage: Use /warplist to see all warps.
  lobby:
    description: Vai ate o spawn.
    aliases: [spawn , hub]
    permission: fallcraft.module.essentials.spawn
    usage: Use /lobby para ir ate o spawn.
  setlobby:
    description: Define o ponto do lobby.
    permission: fallcraft.module.essentials.setspawn
    usage: Use /setlobby para definir o ponto do spawn.
  v:
    description: Alterna entre visivel e invisivel.
    permission: fallcraft.module.essentials.v
    usage: Use /v para alternar.
  fly:
    description: Alterna entre voar e nao voar.
    permission: fallcraft.module.essentials.fly
    usage: Use /fly para alternar.
  gm:
    description: Define o modo de jogo.
    permission: fallcraft.module.essentials.gm
    usage: Use /gm <0|1|2|3>.
  tp:
    description: Teleporta para outro player.
    permission: fallcraft.module.essentials.tp
    usage: Use /tp <player> [player].
  tpall:
    description: Teleporta todos players do servidor para um unico player.
    permission: fallcraft.module.essentials.tpall
    usage: Use /tpall.
  reloadall:
    description: Kicka todos do servidor e o reinicia.
    permission: fallcraft.module.essentials.reloadall
    usage: Use /reloadall.
  spy:
    description: Habilita ou desabilita o modo spy.
    permission: fallcraft.module.essentials.spy
    usage: Use /spy.
  kit:
    description: Abre o menu para ver todos os kits disponiveis.
    usage: Use /kit.
  createkit:
    description: Cria um novo kit.
    permission: fallcraft.module.kitcreate
    usage: Use /createkit <nome> <posicao> <horas> [permissao].
  delkit:
    description: Deleta um kit.
    permission: fallcraft.module.delkit
    usage: Use /delkit <nome>.
  home:
    description: Deleta um kit.
    permission: fallcraft.module.home
    usage: Use /home <Home_Name>.
  delhome:
    description: Deleta um kit.
    permission: fallcraft.module.delhome
    usage: Use /delhome <nome>.
  sethome:
    description: Deleta um kit.
    permission: fallcraft.module.sethome
    usage: Use /sethome <nome>.
  homelist:
    description: Deleta um kit.
    permission: fallcraft.module.homelist
    usage: Use /homelist.
permissions:
  fallcraft.module.warp.*:
    description: Da acesso a todos comandos do Warp
    children:
      fallcraft.module.warp.list: true
      fallcraft.module.warp.use: true
      fallcraft.module.warp.admin: true
  fallcraft.module.essentials:
    description: Acesso a todos os modulos de essentials
    children:
      fallcraft.module.essentials.spawn: true
