config:


  precos:
    quantidade: 4   #para cada número adicionado deve-se repetir o padrão.

    1:          #Player
      mao: 100

    2:          #Beta
      mao: 90

    3:          #Ouro
      mao: 80

    4:          #Dima
      mao: 70


  #Permissão para uso: fallcraft.module.reparar_<número>
  #Permissão para reparar gratuitamente: fallcraft.module.reparar_gratis

  simbolo: "$"  #Exemplo: $1000