name: FallCraftSystem
version: 1.0-SNAPSHOT
main: fallcraftsystem.core.FallCraftSystem
api-version: 1.8.8
depend: [WorldGuard]
commands:
  setwarp:
    description: Defino um novo warp.
    permission: fallcraft.module.warp.admin
    usage: Use /setwarp <Name> <Position> [Permission] para definir um warp.
  delwarp:
    description: Deleta um warp.
    permission: fallcraft.module.warp.admin
    usage: Use /delwarp <Name> tpara deletar um warp.
  warp:
    description: Abre o menu de warps.
    permission: fallcraft.module.warp.use
    usage: Use /warp <warp name> to teleport.
  warplist:
    description: See the all warps.
    permission: fallcraft.module.warp.list
    usage: Use /warplist to see all warps.
  lobby:
    description: Vai ate o spawn.
    aliases: [spawn , hub]
    permission: fallcraft.module.essentials.spawn
    usage: Use /lobby para ir ate o spawn.
  setlobby:
    description: Define o ponto do lobby.
    permission: fallcraft.module.essentials.setspawn
    usage: Use /setlobby para definir o ponto do spawn.
  v:
    description: Alterna entre visivel e invisivel.
    permission: fallcraft.module.essentials.v
    usage: Use /v para alternar.
  fly:
    description: Alterna entre voar e nao voar.
    permission: fallcraft.module.essentials.fly
    usage: Use /fly para alternar.
  inv:
    description: Alterna entre visivel e invisivel.
    permission: fallcraft.module.essentials.inv
    usage: Use /inv para alternar.
  gm:
    description: Define o modo de jogo.
    permission: fallcraft.module.essentials.gm
    usage: Use /gm <0|1|2|3>.
  tp:
    description: Teleporta para outro player.
    permission: fallcraft.module.essentials.tp
    usage: Use /tp <player> [player].
  tphere:
    description: Puxa um jogador.
    permission: fallcraft.module.essentials.tphere
    usage: Use /tphere <Player>.
    aliases:
      - tph
      - puxar
  tpall:
    description: Teleporta todos players do servidor para um unico player.
    permission: fallcraft.module.essentials.tpall
    usage: Use /tpall.
  reloadall:
    description: Kicka todos do servidor e o reinicia.
    permission: fallcraft.module.essentials.reloadall
    usage: Use /reloadall.
  spy:
    description: Habilita ou desabilita o modo spy.
    permission: fallcraft.module.essentials.spy
    usage: Use /spy.
  kit:
    description: Abre o menu para ver todos os kits disponiveis.
    usage: Use /kit.
  createkit:
    description: Cria um novo kit.
    permission: fallcraft.module.kitcreate
    usage: Use /createkit <nome> <posicao> <horas> [permissao].
  delkit:
    description: Deleta um kit.
    permission: fallcraft.module.delkit
    usage: Use /delkit <nome>.
  home:
    description: Teleporta para a casa.
    permission: fallcraft.module.home
    usage: Use /home <Home_Name>.
  delhome:
    description: Apaga a casa.
    permission: fallcraft.module.delhome
    usage: Use /delhome <nome>.
  sethome:
    description: Salva a casa.
    permission: fallcraft.module.sethome
    usage: Use /sethome <nome>.
  aviso:
    description: Envia um aviso ao server inteiro.
    permission: fallcraft.module.aviso.admin
    usage: Use /aviso <Aviso>.
  homelist:
    description: Lista todas as casas.
    permission: fallcraft.module.homelist
    usage: Use /homelist.
  reloadfall:
    description: Restarta todos arquivos de configuracao
    permission: fallcraft.admin.reloadfall
    usage: Use /reloadfall
  discord:
    description: Get discord.
    usage: Use /discord.
  coin:
    description: Use Coin System
    usage: Use /coin

  ajudastaff:
    description: Chat de ajuda
    usage: Use /ajudastaff
    aliases:
      - ajuda
      - helpop
      - as
  echest:
    description: Abre o enderchest
    permission: fallcraft.module.echest_use
    usage: §cUse /echest
    aliases:
      - ec
      - enderchest
  chest:
    description: Abre um baú virtual
    permission: fallcraft.chest.open
    usage: §cUse /chest
  craftingtable:
    description: Abre uma crafting table virtual
    permission: fallcraft.modules.craftingtable
    usage: §7Use /craftingtable
    aliases:
      - ct
      - workbench
      - wb
      - craft
  luz:
    description: Ativa visão noturna.
    permission: fallcraft.modules.luz
    usage: Use /luz.
  blocks:
    description: Transforma minérios em blocos
    permission: fallcraft.modules.blocks
    usage: Use /block
    aliases:
      - compactar
      - compact
  fcscoreboard:
    description: liga e desliga a scoreboard.
    usage: §cUse /fcscoreboard <on/off>
    aliases:
      - fcs
      - fcscore
  invsee:
    description: Abre o inventário de um jogador.
    usage: Use /invsee <jogador>.
    permission: fallcraft.module.invsee
  reparo:
    description: Repara seus itens
    usage: Use /reparo <mão/tudo>
    aliases:
      - fix
      - reparo
  tpa:
    description: Pede para teleportar para um jogador
    usage: Use /tpa <jogador>.
  tpahere:
    description: Pede para teleportar um jogador para si
    usage: Use /tpahere <jogador>.
  tpaccept:
    description: aceita o pedido
  tpdeny:
    description: rejeita o pedido
  tpatoggle:
    description: Liga/desliga os pedidos de teleporte
    permission: fallcraft.module.tpa_toggle
    aliases:
      - tpat
  tpevento:
    description: Manda um /tpahere para todos os jogadores online.
    permission: fallcraft.module.tpevento
    aliases:
      - tpe
      - tpaevento
      - tpae
  automessage:
    description: Manda mensagens automáticamente no intervalo de tempo definido nas configs.
    permission: fallcraft.module.automessage

  permissions:
  fallcraft.module.warp.*:
    description: Da acesso a todos comandos do Warp
    children:
      fallcraft.module.warp.list: true
      fallcraft.module.warp.use: true
      fallcraft.module.warp.admin: true
  fallcraft.module.essentials:
    description: Acesso a todos os modulos de essentials
    children:
      fallcraft.module.essentials.spawn: true
