name: FallCraftSystem
version: 1.0-SNAPSHOT
main: fallcraftsystem.core.FallCraftSystem
api-version: 1.8.8
depend: [WorldGuard]
commands:
  setwarp:
    description: Defino um novo warp.
    permission: fallcraft.module.warp.admin
    usage: Use /setwarp <Name> <Position> [Permission] para definir um warp.
  delwarp:
    description: Deleta um warp.
    permission: fallcraft.module.warp.admin
    usage: Use /delwarp <Name> tpara deletar um warp.
  warp:
    description: Abre o menu de warps.
    permission: fallcraft.module.warp.use
    usage: Use /warp <warp name> to teleport.
  warplist:
    description: See the all warps.
    permission: fallcraft.module.warp.list
    usage: Use /warplist to see all warps.
  lobby:
    description: Vai ate o spawn.
    aliases: [spawn , hub]
    permission: fallcraft.module.essentials.spawn
    usage: Use /lobby para ir ate o spawn.
  setlobby:
    description: Define o ponto do lobby.
    permission: fallcraft.module.essentials.setspawn
    usage: Use /setlobby para definir o ponto do spawn.
  v:
    description: Alterna entre visivel e invisivel.
    permission: fallcraft.module.essentials.v
    usage: Use /v para alternar.
  fly:
    description: Alterna entre voar e nao voar.
    permission: fallcraft.module.essentials.fly
    usage: Use /fly para alternar.
  inv:
    description: Alterna entre visivel e invisivel.
    permission: fallcraft.module.essentials.inv
    usage: Use /inv para alternar.
  gm:
    description: Define o modo de jogo.
    permission: fallcraft.module.essentials.gm
    usage: Use /gm <0|1|2|3>.
  tp:
    description: Teleporta para outro player.
    permission: fallcraft.module.essentials.tp
    usage: Use /tp <player> [player].
  tphere:
    description: Puxa um jogador.
    permission: fallcraft.module.essentials.tphere
    usage: Use /tphere <Player>.
    aliases:
      - tph
      - puxar
  tpall:
    description: Teleporta todos players do servidor para um unico player.
    permission: fallcraft.module.essentials.tpall
    usage: Use /tpall.
  reloadall:
    description: Kicka todos do servidor e o reinicia.
    permission: fallcraft.module.essentials.reloadall
    usage: Use /reloadall.
  spy:
    description: Habilita ou desabilita o modo spy.
    permission: fallcraft.module.essentials.spy
    usage: Use /spy.
  kit:
    description: Abre o menu para ver todos os kits disponiveis.
    usage: Use /kit.
  createkit:
    description: Cria um novo kit.
    permission: fallcraft.module.kitcreate
    usage: Use /createkit <nome> <posicao> <horas> [permissao].
  delkit:
    description: Deleta um kit.
    permission: fallcraft.module.delkit
    usage: Use /delkit <nome>.
  home:
    description: Deleta um kit.
    permission: fallcraft.module.home
    usage: Use /home <Home_Name>.
  delhome:
    description: Deleta um kit.
    permission: fallcraft.module.delhome
    usage: Use /delhome <nome>.
  sethome:
    description: Deleta um kit.
    permission: fallcraft.module.sethome
    usage: Use /sethome <nome>.
  aviso:
    description: Envia um aviso ao server inteiro.
    permission: fallcraft.module.aviso.admin
    usage: Use /aviso <Aviso>.
  homelist:
    description: Deleta um kit.
    permission: fallcraft.module.homelist
    usage: Use /homelist.
  reloadfall:
    description: Restarta todos arquivos de configuracao
    permission: fallcraft.admin.reloadfall
    usage: Use /reloadfall
  discord:
    description: Get discord.
    usage: Use /discord.
  coin:
    description: Use Coin System
    usage: Use /coin

  ajudastaff:
    description: Chat de ajuda
    usage: Use /ajudastaff
  echest:
    description: Abre o enderchest
    permission: fallcraft.module.echest_use
    usage: §cUse /echest
    aliases:
      - ec
      - enderchest
  chest:
    description: Abre um baú virtual
    permission: fallcraft.chest.open
    usage: §cUse /chest
  itemajuda:
    permission: fallcraft.modules.item.ajuda
    aliases:
      - iajuda
      - item
  itemnome:
    description: Muda o nome do item segurado (aceita cores)
    permission: fallcraft.modules.item.nome
    usage: §7Use §9/itemnome <nome> §7com um item na mão.
    aliases:
      - inome
      - iname
      - itemname
  itemdesc:
    description: Muda a lore (descrição) de um item (aceita cores)
    permission: fallcraft.modules.item.desc
    usage: §7Use §9/itemdesc <linha> <frase> §c(recomendado usar o /itemname primeiro)
    aliases:
      - idesc
      - itdesc
  itemenchant:
    description: Encanta o item segurado
    permission: fallcraft.modules.item.enchant
    usage: §7Use §9/itemenchant <nome> <valor> §7 (<nome> pode ser 'all') // §9/itemenchant remover <nome>
    aliases:
      - itenchant
      - ienchant
      - iench
      - itench
  editar:
    description: Edita a placa olhada
  craftingtable:
    description: Abre uma crafting table virtual
    permission: fallcraft.modules.craftingtable
    usage: §7Use /craftingtable
    aliases:
      - ct
      - workbench
      - wb
      - craft
  luz:
    description: Ativa visão noturna.
    permission: fallcraft.modules.luz
    usage: Use /luz.
  blocks:
    description: Transforma minérios em blocos
    permission: fallcraft.modules.blocks
    usage: Use /block
    aliases:
      - compactar
      - compact
  fcscoreboard:
    description: liga e desliga a scoreboard.
    usage: §cUse /fcscoreboard <on/off>
    aliases:
      - fcs
      - fcscore
  invsee:
    description: Abre o inventário de um jogador.
    usage: Use /invsee <jogador>.
    permission: fallcraft.module.invsee
  reparo:
    description: Repara seus itens
    usage: Use /reparo <mão/tudo>
    aliases:
      - fix
      - reparo

  permissions:
  fallcraft.module.warp.*:
    description: Da acesso a todos comandos do Warp
    children:
      fallcraft.module.warp.list: true
      fallcraft.module.warp.use: true
      fallcraft.module.warp.admin: true
  fallcraft.module.essentials:
    description: Acesso a todos os modulos de essentials
    children:
      fallcraft.module.essentials.spawn: true
